---
apiVersion: kubeone.io/v1beta1
kind: KubeOneCluster
name: k8s-cedi-dev

versions:
  kubernetes: "1.21.3"

clusterNetwork:
  # the subnet used for pods (default: 10.244.0.0/16)
  podSubnet: "10.244.0.0/16"
  # the subnet used for services (default: 10.96.0.0/12)
  serviceSubnet: "10.96.0.0/12"
  # the domain name used for services (default: cluster.local)
  serviceDomainName: "cluster.local"
  # a nodePort range to reserve for services (default: 30000-32767)
  nodePortRange: "30000-32767"
  # CNI plugin of choice. CNI can not be changed later at upgrade time.
  cni:
    # Only one CNI plugin can be defined at the same time
    # Supported CNI plugins:
    # * canal
    # * weave-net
    # * cilium
    # * external - The CNI plugin can be installed as an addon or manually
    # canal:
    #   # MTU represents the maximum transmission unit.
    #   # Default MTU value depends on the specified provider:
    #   # * AWS - 8951 (9001 AWS Jumbo Frame - 50 VXLAN bytes)
    #   # * GCE - 1410 (GCE specific 1460 bytes - 50 VXLAN bytes)
    #   # * Hetzner - 1400 (Hetzner specific 1450 bytes - 50 VXLAN bytes)
    #   # * OpenStack - 1400 (OpenStack specific 1450 bytes - 50 VXLAN bytes)
    #   # * Default - 1450
    #   mtu: 1450
    cilium:
      # enableHubble to deploy Hubble relay and UI
      enableHubble: true
      # kubeProxyReplacement defines weather cilium relies on underlying Kernel support to replace kube-proxy functionality by eBPF (strict),
      # or disables a subset of those features so cilium does not bail out if the kernel support is missing (disabled).
      kubeProxyReplacement: "disabled"
    # weaveNet:
    #   # When true is set, secret will be automatically generated and
    #   # referenced in appropriate manifests. Currently only weave-net
    #   # supports encryption.
    #   encrypted: true
    # external: {}

cloudProvider:
  # Set the kubelet flag '--cloud-provider=external' and deploy the external CCM for supported providers
  external: true
  hetzner: {}

# Controls which container runtime will be installed on instances.
# By default:
# * Docker will be installed for Kubernetes clusters up to 1.20
# * containerd will be installed for Kubernetes clusters 1.21+
# Currently, it's not possible to migrate existing clusters from one to another
# container runtime, however, migration from Docker to containerd is planned
# for one of the upcoming KubeOne releases.
# Only one container runtime can be present at the time.
#
# Note: Kubernetes has announced deprecation of Docker (dockershim) support.
# It's expected that the Docker support will be removed in Kubernetes 1.22.
# It's highly advised to use containerd for all newly created clusters.
containerRuntime:
  # Installs containerd container runtime.
  # Default for 1.21+ Kubernetes clusters.
  containerd: {}
  # Installs Docker container runtime.
  # Default for Kubernetes clusters up to 1.20.
  # This option will be removed once Kubernetes 1.21 reaches EOL.
  # docker: {}

features:
  # Enables and configures audit log backend.
  # More info: https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#log-backend
  staticAuditLog:
    enable: false
    config:
      # PolicyFilePath is a path on local file system to the audit policy manifest
      # which defines what events should be recorded and what data they should include.
      # PolicyFilePath is a required field.
      # More info: https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#audit-policy
      policyFilePath: ""
      # LogPath is path on control plane instances where audit log files are stored
      logPath: "/var/log/kubernetes/audit.log"
      # LogMaxAge is maximum number of days to retain old audit log files
      logMaxAge: 30
      # LogMaxBackup is maximum number of audit log files to retain
      logMaxBackup: 3
      # LogMaxSize is maximum size in megabytes of audit log file before it gets rotated
      logMaxSize: 100
  # Enables dynamic audit logs.
  # After enablig this, operator should create auditregistration.k8s.io/v1alpha1
  # AuditSink object.
  # More info: https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#dynamic-backend
  dynamicAuditLog:
    enable: false
  # Opt-out from deploying metrics-server
  # more info: https://github.com/kubernetes-incubator/metrics-server
  metricsServer:
    # enabled by default
    enable: true

systemPackages:
  # will add Docker and Kubernetes repositories to OS package manager
  configureRepositories: true # it's true by default

# Addons are Kubernetes manifests to be deployed after provisioning the cluster
addons:
  enable: true
  # In case when the relative path is provided, the path is relative
  # to the KubeOne configuration file.
  # This path must be always provided and the directory must exist, even if
  # using only embedded addons.
  path: "./addons"
  # addons is used to enable addons embedded in the KubeOne binary.
  # Currently backups-restic, default-storage-class, and unattended-upgrades are
  # available addons.
  # Check out the documentation to find more information about what are embedded
  # addons and how to use them:
  # https://docs.kubermatic.com/kubeone/v1.3/guides/addons/
  addons:
    - name: cluster-autoscaler
    - name: unattended-upgrades
    - name: argocd

# If the cluster runs on bare metal or an unsupported cloud provider,
# you can disable the machine-controller deployment entirely. In this
# case, anything you configure in your "workers" sections is ignored.
machineController:
  deploy: true
