---
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
name: av0

versions:
  kubernetes: "1.23.1"

clusterNetwork:
  # the subnet used for pods (default: 10.244.0.0/16)
  podSubnet: "10.244.0.0/16"
  # the subnet used for services (default: 10.96.0.0/12)
  serviceSubnet: "10.96.0.0/12"
  # the domain name used for services (default: cluster.local)
  serviceDomainName: "cluster.local"
  # a nodePort range to reserve for services (default: 30000-32767)
  nodePortRange: "30000-32767"
  # CNI plugin of choice. CNI can not be changed later at upgrade time.
  cni:
    # Only one CNI plugin can be defined at the same time
    # Supported CNI plugins:
    # * canal
    # * weave-net
    # * cilium
    # * external - The CNI plugin can be installed as an addon or manually
    canal:
      # MTU represents the maximum transmission unit.
      # Default MTU value depends on the specified provider:
      # * AWS - 8951 (9001 AWS Jumbo Frame - 50 VXLAN bytes)
      # * GCE - 1410 (GCE specific 1460 bytes - 50 VXLAN bytes)
      # * Hetzner - 1400 (Hetzner specific 1450 bytes - 50 VXLAN bytes)
      # * OpenStack - 1400 (OpenStack specific 1450 bytes - 50 VXLAN bytes)
      # * Default - 1450
      mtu: 1400
    #cilium:
    #  # enableHubble to deploy Hubble relay and UI
    #  enableHubble: true
    #  # kubeProxyReplacement defines weather cilium relies on underlying Kernel support to replace kube-proxy functionality by eBPF (strict),
    #  # or disables a subset of those features so cilium does not bail out if the kernel support is missing (disabled).
    #  kubeProxyReplacement: "disabled"
    # weaveNet:
    #   # When true is set, secret will be automatically generated and
    #   # referenced in appropriate manifests. Currently only weave-net
    #   # supports encryption.
    #   encrypted: true
    # external: {}

cloudProvider:
  # Set the kubelet flag '--cloud-provider=external' and deploy the external CCM for supported providers
  external: true
  hetzner: {}

# Addons are Kubernetes manifests to be deployed after provisioning the cluster
addons:
  enable: true
  # In case when the relative path is provided, the path is relative
  # to the KubeOne configuration file.
  # This path must be always provided and the directory must exist, even if
  # using only embedded addons.
  path: "./addons"
  # addons is used to enable addons embedded in the KubeOne binary.
  # Currently backups-restic, default-storage-class, and unattended-upgrades are
  # available addons.
  # Check out the documentation to find more information about what are embedded
  # addons and how to use them:
  # https://docs.kubermatic.com/kubeone/v1.3/guides/addons/
  addons:
    - name: cluster-autoscaler
    - name: default-namespaces
