name: "Terraform KubeOne"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      kubeconfig:
        description: 'Generate Kubeconfig'
        required: true
        default: 'false'

jobs:
  lint:
    name: "Lint Configuration"
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Checkout
        uses: actions/checkout@v2

      - name: Template machine-deployment file
        run: |
          export NETWORK_ID=`jq '.kubeone_hosts.value.control_plane.network_id' -r < output.json`
          export CLUSTER_NAME=`jq '.kubeone_hosts.value.control_plane.cluster_name' -r < output.json`
          export CLUSTER_VERSION=`yq e -j < kubeone.yaml | jq '.versions.kubernetes' -r`
          envsubst < ./machinedeployment.yaml.tpl > ./machinedeployment.yaml

      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          format: github
          config_file: .yamllint.yml

      - name: Terraform format check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform init && terraform validate

  terraform:
    name: "[Terraform] Deploy Infrastructure"
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        continue-on-error: true

      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`${process.env.PLAN}\`\`\`
            </details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

      - name: Terraform Output
        run: terraform output -json > output.json

      - name: Archive terraform output
        uses: actions/upload-artifact@v2
        with:
          name: output.json
          path: output.json

  kubeone:
    name: "[KubeOne] Provision K8s Cluster"
    runs-on: ubuntu-latest
    needs: terraform
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Setup Kubeone
        uses: cedi/gh-action-kubeone@v1
        with:
          version: main

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download output.json
        uses: actions/download-artifact@v2
        with:
          name: output.json

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519
          config: |
            *
              StrictHostKeyChecking=no
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Template credentials file
        run: envsubst < ./credentials.yaml.tpl > ./credentials.yaml
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}

      - name: KubeOne Apply
        run: kubeone apply --manifest kubeone.yaml --credentials credentials.yaml --tfjson output.json --auto-approve

      - name: KubeOne Status
        run: kubeone status --manifest kubeone.yaml --credentials credentials.yaml --tfjson output.json

  kubectl:
    name: "[kubectl] Apply initial configuration"
    runs-on: ubuntu-latest
    needs: kubeone
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Setup Kubeone
        uses: cedi/gh-action-kubeone@v1
        with:
          version: main

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(<kubectl.sha256) kubectl" | sha256sum --check
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download output.json
        uses: actions/download-artifact@v2
        with:
          name: output.json

      - name: Template credentials file
        run: envsubst < ./credentials.yaml.tpl > ./credentials.yaml
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519
          config: |
            *
              StrictHostKeyChecking=no
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Obtain kubeconfig
        run: kubeone kubeconfig --manifest kubeone.yaml --credentials credentials.yaml --tfjson output.json > kubeconfig

      - name: Archive kubeconfig
        uses: actions/upload-artifact@v2
        if: ${{ github.event.inputs.kubeconfig == 'true' }}
        with:
          name: kubeconfig
          path: kubeconfig

      - name: Template machine-deployment file
        run: |
          export NETWORK_ID=`jq '.kubeone_hosts.value.control_plane.network_id' -r < output.json`
          export CLUSTER_NAME=`jq '.kubeone_hosts.value.control_plane.cluster_name' -r < output.json`
          export CLUSTER_VERSION=`yq e -j < kubeone.yaml | jq '.versions.kubernetes' -r`
          envsubst < ./machinedeployment.yaml.tpl > ./machinedeployment.yaml

      - name: Apply MachineDeployment
        run: kubectl apply -f ./machinedeployment.yaml
        env:
          KUBECONFIG: ./kubeconfig

      - name: Install meta ArgoCD Application
        run: |
          git clone https://github.com/cedi-dev/k8s-manifests.git
          cd k8s-manifests
          kubectl apply -f argo-apps/k8s-cedi-dev.yaml
