name: "Terraform KubeOne"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      kubeconfig:
        description: 'Generate Kubeconfig'
        required: true
        default: 'false'

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        continue-on-error: true

      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`${process.env.PLAN}\`\`\`
            </details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

      - name: Terraform Output
        run: terraform output -json > output.json

      - name: Archive terraform output
        uses: actions/upload-artifact@v2
        with:
          name: output.json
          path: output.json
  
  kubeone:
    name: "Kubeone"
    runs-on: ubuntu-latest
    needs: terraform
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download output.json
        uses: actions/download-artifact@v2
        with:
          name: output.json

      - name: Install KubeOne
        run: |
          curl --version  
          curl -L https://github.com/kubermatic/kubeone/releases/download/v1.2.1/kubeone_1.2.1_linux_amd64.zip -o kubeone.zip
          unzip kubeone.zip -d bin
          ./bin/kubeone version

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519
          config: |
            *
              StrictHostKeyChecking=no
          known_hosts: unnecessary
          if_key_exists: replace
      
      - name: KubeOne Apply
        run: ./bin/kubeone apply --manifest kubeone.yaml --tfjson output.json --auto-approve --verbose
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}

      - name: KubeOne Status
        run: ./bin/kubeone status --manifest kubeone.yaml --tfjson output.json
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}

      - name: KubeOne Kubeconfig
        run: ./bin/kubeone kubeconfig --manifest kubeone.yaml --tfjson output.json > kubeconfig
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}

      - name: Archive kubeconfig
        uses: actions/upload-artifact@v2
        if: ${{ github.event.inputs.kubeconfig == 'true' }}
        with:
          name: kubeconfig
          path: kubeconfig

      - name: Template machinedeployment.yaml
        run: |
          export NETWORK_ID="$(jq '.kubeone_hosts.value.control_plane.network_id' < output.json)"
          export VERSION="$(cat kubeone.yaml | grep -A 1 versions | grep kubernetes | awk '{print $2}')"
          export CLUSTERNAME="$(cat kubeone.yaml | grep "name:" | awk '{print $2}')"
          envsubst < machinedeployment.yaml.tpl > machinedeployment.yaml
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
          REPLICAS: 3
          SERVER_TYPE: "cx21"
          LOCATION: "fsn1"
          OS: "ubuntu"
          IMAGE: "ubuntu-20.04"

      - name: Debug machinedeployment.yaml
        run: cat machinedeployment.yaml

      - name: Archive terraform output
        uses: actions/upload-artifact@v2
        with:
          name: machinedeployment.yaml
          path: machinedeployment.yaml

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(<kubectl.sha256) kubectl" | sha256sum --check
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Install kubectl
        run: |
          kubectl version
          kubectl get pods -A
        env:
          KUBECONFIG: ./kubeconfig
          